Resources:
  pineappleCheckLambdaHandlerServiceRoleFC4E3211:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: TheStateMachineStack/pineappleCheckLambdaHandler/ServiceRole/Resource
  pineappleCheckLambdaHandlerFDB742D5:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters41aa454f2e71f092cd00bef03cc5d6c8177965f5e55f1b3b096e5108c63ca413S3Bucket7344BAF9
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters41aa454f2e71f092cd00bef03cc5d6c8177965f5e55f1b3b096e5108c63ca413S3VersionKey2A28EC85
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters41aa454f2e71f092cd00bef03cc5d6c8177965f5e55f1b3b096e5108c63ca413S3VersionKey2A28EC85
      Role:
        Fn::GetAtt:
          - pineappleCheckLambdaHandlerServiceRoleFC4E3211
          - Arn
      Handler: orderPizza.handler
      Runtime: nodejs14.x
    DependsOn:
      - pineappleCheckLambdaHandlerServiceRoleFC4E3211
    Metadata:
      aws:cdk:path: TheStateMachineStack/pineappleCheckLambdaHandler/Resource
      aws:asset:path: asset.41aa454f2e71f092cd00bef03cc5d6c8177965f5e55f1b3b096e5108c63ca413
      aws:asset:property: Code
  handleFailureLambdaHandlerServiceRole3BEB3C5B:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: TheStateMachineStack/handleFailureLambdaHandler/ServiceRole/Resource
  handleFailureLambdaHandler25AADEF8:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters41aa454f2e71f092cd00bef03cc5d6c8177965f5e55f1b3b096e5108c63ca413S3Bucket7344BAF9
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters41aa454f2e71f092cd00bef03cc5d6c8177965f5e55f1b3b096e5108c63ca413S3VersionKey2A28EC85
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters41aa454f2e71f092cd00bef03cc5d6c8177965f5e55f1b3b096e5108c63ca413S3VersionKey2A28EC85
      Role:
        Fn::GetAtt:
          - handleFailureLambdaHandlerServiceRole3BEB3C5B
          - Arn
      Handler: handleFailure.handler
      Runtime: nodejs14.x
    DependsOn:
      - handleFailureLambdaHandlerServiceRole3BEB3C5B
    Metadata:
      aws:cdk:path: TheStateMachineStack/handleFailureLambdaHandler/Resource
      aws:asset:path: asset.41aa454f2e71f092cd00bef03cc5d6c8177965f5e55f1b3b096e5108c63ca413
      aws:asset:property: Code
  deliverPizzaLambdaHandlerServiceRole6C40EE01:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: TheStateMachineStack/deliverPizzaLambdaHandler/ServiceRole/Resource
  deliverPizzaLambdaHandler15A6A3CC:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters41aa454f2e71f092cd00bef03cc5d6c8177965f5e55f1b3b096e5108c63ca413S3Bucket7344BAF9
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters41aa454f2e71f092cd00bef03cc5d6c8177965f5e55f1b3b096e5108c63ca413S3VersionKey2A28EC85
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters41aa454f2e71f092cd00bef03cc5d6c8177965f5e55f1b3b096e5108c63ca413S3VersionKey2A28EC85
      Role:
        Fn::GetAtt:
          - deliverPizzaLambdaHandlerServiceRole6C40EE01
          - Arn
      Handler: deliverPizza.handler
      Runtime: nodejs14.x
    DependsOn:
      - deliverPizzaLambdaHandlerServiceRole6C40EE01
    Metadata:
      aws:cdk:path: TheStateMachineStack/deliverPizzaLambdaHandler/Resource
      aws:asset:path: asset.41aa454f2e71f092cd00bef03cc5d6c8177965f5e55f1b3b096e5108c63ca413
      aws:asset:property: Code
  StateMachineRoleB840431D:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                Fn::Join:
                  - ""
                  - - states.
                    - Ref: AWS::Region
                    - .amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: TheStateMachineStack/StateMachine/Role/Resource
  StateMachineRoleDefaultPolicyDF1E6607:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - xray:PutTraceSegments
              - xray:PutTelemetryRecords
              - xray:GetSamplingRules
              - xray:GetSamplingTargets
            Effect: Allow
            Resource: "*"
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - pineappleCheckLambdaHandlerFDB742D5
                - Arn
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - deliverPizzaLambdaHandler15A6A3CC
                - Arn
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - handleFailureLambdaHandler25AADEF8
                - Arn
        Version: "2012-10-17"
      PolicyName: StateMachineRoleDefaultPolicyDF1E6607
      Roles:
        - Ref: StateMachineRoleB840431D
    Metadata:
      aws:cdk:path: TheStateMachineStack/StateMachine/Role/DefaultPolicy/Resource
  StateMachine2E01A3A5:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn:
        Fn::GetAtt:
          - StateMachineRoleB840431D
          - Arn
      DefinitionString:
        Fn::Join:
          - ""
          - - '{"StartAt":"Order Pizza Job","States":{"Order Pizza Job":{"Next":"With Pineapple?","Retry":[{"ErrorEquals":["Lambda.ServiceException","Lambda.AWSLambdaException","Lambda.SdkClientException"],"IntervalSeconds":2,"MaxAttempts":6,"BackoffRate":2}],"Type":"Task","InputPath":"$.flavour","ResultPath":"$.pineappleAnalysis","Resource":"'
            - Fn::GetAtt:
                - pineappleCheckLambdaHandlerFDB742D5
                - Arn
            - '"},"With Pineapple?":{"Type":"Choice","Choices":[{"Variable":"$.pineappleAnalysis.containsPineapple","BooleanEquals":true,"Next":"Handle Failure"}],"Default":"Deliver Pizza"},"Deliver Pizza":{"Next":"Your pizza is on the way!","Retry":[{"ErrorEquals":["Lambda.ServiceException","Lambda.AWSLambdaException","Lambda.SdkClientException"],"IntervalSeconds":2,"MaxAttempts":6,"BackoffRate":2}],"Type":"Task","InputPath":"$.address","ResultPath":"$.deliveryDetails","Resource":"'
            - Fn::GetAtt:
                - deliverPizzaLambdaHandler15A6A3CC
                - Arn
            - '"},"Your pizza is on the way!":{"Type":"Succeed","OutputPath":"$.deliveryDetails"},"Handle Failure":{"Next":"Sorry, We Dont add Pineapple","Retry":[{"ErrorEquals":["Lambda.ServiceException","Lambda.AWSLambdaException","Lambda.SdkClientException"],"IntervalSeconds":2,"MaxAttempts":6,"BackoffRate":2}],"Type":"Task","InputPath":"$.pineappleAnalysis.containsPineapple","ResultPath":"$.failureResult","Resource":"'
            - Fn::GetAtt:
                - handleFailureLambdaHandler25AADEF8
                - Arn
            - '"},"Sorry, We Dont add Pineapple":{"Type":"Fail","Error":"Failed To Make Pizza","Cause":"They asked for Pineapple"}},"TimeoutSeconds":300}'
      StateMachineType: EXPRESS
      TracingConfiguration:
        Enabled: true
    DependsOn:
      - StateMachineRoleDefaultPolicyDF1E6607
      - StateMachineRoleB840431D
    Metadata:
      aws:cdk:path: TheStateMachineStack/StateMachine/Resource
  HttpApiRole79B5C31A:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      Policies:
        - PolicyDocument:
            Statement:
              - Action: states:StartSyncExecution
                Effect: Allow
                Resource:
                  Ref: StateMachine2E01A3A5
            Version: "2012-10-17"
          PolicyName: AllowSFNExec
    Metadata:
      aws:cdk:path: TheStateMachineStack/HttpApiRole/Resource
  thestatemachineapi69C81CC4:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: the-state-machine-api
      ProtocolType: HTTP
    Metadata:
      aws:cdk:path: TheStateMachineStack/the-state-machine-api/Resource
  thestatemachineapiDefaultStageE23A2C15:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId:
        Ref: thestatemachineapi69C81CC4
      StageName: $default
      AutoDeploy: true
    Metadata:
      aws:cdk:path: TheStateMachineStack/the-state-machine-api/DefaultStage/Resource
  Integ:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Ref: thestatemachineapi69C81CC4
      IntegrationType: AWS_PROXY
      ConnectionType: INTERNET
      CredentialsArn:
        Fn::GetAtt:
          - HttpApiRole79B5C31A
          - Arn
      IntegrationSubtype: StepFunctions-StartSyncExecution
      PayloadFormatVersion: "1.0"
      RequestParameters:
        Input: $request.body
        StateMachineArn:
          Ref: StateMachine2E01A3A5
      TimeoutInMillis: 10000
    Metadata:
      aws:cdk:path: TheStateMachineStack/Integ
  DefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: thestatemachineapi69C81CC4
      RouteKey: $default
      Target:
        Fn::Join:
          - ""
          - - integrations/
            - Ref: Integ
    Metadata:
      aws:cdk:path: TheStateMachineStack/DefaultRoute
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAAA11R0WrDMAz8lr077rLB2N7WBsYKGyvpF2iOmqpJ7GDJKSXk32e7K4w96U6cpDu71GX5ou/vXuHMhWm61WycRz3vBUyn1swoEbZkW1U5y+KDEVUd7A48DCjoE/kKMobcrpFd8AYTjvqGhJxdVFo+9zB8N6Dnt2BNaifNDS+KYNBz7fo8muvO9WQu+VhGi+LHApIj1tlY5HoTTIeyAUbFguPhdx8XAtyx/sg3t3Zy3T9B9AHUq30wBrFR1dFRtB2zCn6COZLNRv7yGGOkNvIzXKYHPb+LjOuRkiyVRNNT3eauYGsFWw+3vLULgsuyKOsa1CdeTeWzLp/iB5yYqPDBCg2o62v9Aeuv8HedAQAA
    Metadata:
      aws:cdk:path: TheStateMachineStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Parameters:
  AssetParameters41aa454f2e71f092cd00bef03cc5d6c8177965f5e55f1b3b096e5108c63ca413S3Bucket7344BAF9:
    Type: String
    Description: S3 bucket for asset "41aa454f2e71f092cd00bef03cc5d6c8177965f5e55f1b3b096e5108c63ca413"
  AssetParameters41aa454f2e71f092cd00bef03cc5d6c8177965f5e55f1b3b096e5108c63ca413S3VersionKey2A28EC85:
    Type: String
    Description: S3 key for asset version "41aa454f2e71f092cd00bef03cc5d6c8177965f5e55f1b3b096e5108c63ca413"
  AssetParameters41aa454f2e71f092cd00bef03cc5d6c8177965f5e55f1b3b096e5108c63ca413ArtifactHash2B548B64:
    Type: String
    Description: Artifact hash for asset "41aa454f2e71f092cd00bef03cc5d6c8177965f5e55f1b3b096e5108c63ca413"
Outputs:
  HTTPAPIUrl:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: thestatemachineapi69C81CC4
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

